# Run:
#   sudo pip install docker-compose
#   docker-compose up -d
version: "3.7"
services:
  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TIMEZONE}
    volumes:
      - sonarr:/config
      - share1:/data
      - downloads:/downloads
    ports:
      - "8989:8989"
    depends_on:
      - nzbget
      - transmission
    labels:
      - "traefik.enable=true"
      - "traefik.port=8989"
      - "traefik.frontend.rule=Host:${DOMAIN};PathPrefix:/sonarr"
      - "traefik.frontend.auth.basic=${HTTP_AUTH}"
    restart: unless-stopped
  radarr:
    image: linuxserver/radarr
    container_name: radarr
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TIMEZONE}
    volumes:
      - radarr:/config
      - share1:/data
      - downloads:/downloads
    ports:
      - "7878:7878"
    depends_on:
      - nzbget
      - transmission
    labels:
      - "traefik.enable=true"
      - "traefik.port=7878"
      - "traefik.frontend.rule=Host:${DOMAIN};PathPrefix:/radarr"
      - "traefik.frontend.auth.basic=${HTTP_AUTH}"
    restart: unless-stopped
  nzbget:
    image: linuxserver/nzbget
    container_name: nzbget
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TIMEZONE}
    volumes:
      - nzbget:/config
      - downloads:/downloads
      - intermediate:/intermediate
    ports:
      - "6789:6789"
    labels:
      - "traefik.enable=true"
      - "traefik.port=6789"
      - "traefik.frontend.rule=Host:${DOMAIN};PathPrefix:/nzbget"
      - "traefik.frontend.auth.basic=${HTTP_AUTH}"
    restart: unless-stopped
  # Uncomment this section for Transmssion *without* VPN
  # transmission:
  #   image: linuxserver/transmission
  #   container_name: transmission
  #   environment:
  #     PUID: ${PUID}
  #     PGID: ${PGID}
  #     TZ: ${TIMEZONE}
  #   volumes:
  #     - transmission:/config
  #     - downloads:/downloads
  #   ports:
  #     - "9091:9091"
  #     - "51413:51413"
  #     - "51413:51413/udp"
  #   labels:
  #     - "traefik.enable=true"
  #     - "traefik.port=9091"
  #     - "traefik.frontend.rule=Host:${DOMAIN};PathPrefix:/transmission"
  #     - "traefik.frontend.auth.basic=${HTTP_AUTH}"
  #   restart: unless-stopped
  transmission:
    container_name: transmission
    image: haugene/transmission-openvpn:latest-armhf
    cap_add:
      - NET_ADMIN
    devices:
      - "/dev/net/tun"
    restart: unless-stopped
    ports:
      - "9091:9091"
      - "8888:8888"
    dns:
      - 8.8.8.8
      - 8.8.4.4
    sysctls:
      net.ipv6.conf.all.disable_ipv6: 0
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - transmission:/config
      - downloads:/downloads
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      OPENVPN_OPTS: --inactive 3600 --ping 10 --ping-exit 60
      LOCAL_NETWORK: 192.168.0.0/24
      TRANSMISSION_WEB_UI: transmission-web-control
      OPENVPN_PROVIDER: ${OPENVPN_PROVIDER}
      OPENVPN_CONFIG: ${OPENVPN_CONFIG}
      OPENVPN_USERNAME: ${OPENVPN_USERNAME}
      OPENVPN_PASSWORD: ${OPENVPN_PASSWORD}
    labels:
      - "traefik.enable=true"
      - "traefik.port=9091"
      - "traefik.frontend.rule=Host:${DOMAIN};PathPrefix:/transmission"
      - "traefik.frontend.auth.basic=${HTTP_AUTH}"
  emby:
    container_name: emby
    image: emby/embyserver_arm32v7:latest
    ports:
      - "8096:8096"
      - "8920:8920"
    environment:
      UID: ${PUID}
      GID: ${PGID}
      TZ: ${TIMEZONE}
    volumes:
      - emby:/config
      - share1:/share1
    labels:
      - "traefik.enable=true"
      - "traefik.port=8096"
      - "traefik.frontend.rule=Host:${DOMAIN};PathPrefix:/emby"
    restart: unless-stopped
  jackett:
    image: linuxserver/jackett
    container_name: jackett
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TIMEZONE}
    volumes:
      - jackett:/config
      - downloads:/downloads
    ports:
    ports:
      - "9117:9117"
    restart: unless-stopped
  portainer:
    image: portainer/portainer
    command: -H unix:///var/run/docker.sock
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    labels:
      - "traefik.enable=true"
      - "traefik.port=9000"
      - "traefik.frontend.auth.basic=${HTTP_AUTH}"
      - "traefik.passHostHeader=true"
      - "traefik.frontend.redirect.regex=^(.*)/portainer$$"
      - "traefik.frontend.redirect.replacement=$$1/portainer/"
      - "traefik.frontend.rule=Host:${DOMAIN};PathPrefix:/portainer;ReplacePathRegex: ^/portainer/(.*) /$$1"
    restart: always
  traefik:
    container_name: traefik
    image: traefik:alpine
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/rpi-htpc/traefik/traefik.toml:/etc/traefik/traefik.toml
      - /etc/rpi-htpc/traefik/acme.json:/etc/traefik/acme.json
  ddclient:
    image: linuxserver/ddclient
    container_name: ddclient
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TIMEZONE}
    volumes:
      - ddclient:/config
    restart: unless-stopped

volumes:
  # Named config containers
  sonarr:
    name: sonarr
    external: true
  radarr:
    name: radarr
    external: true
  nzbget:
    name: nzbget
    external: true
  transmission:
    name: transmission
    external: true
  jackett:
    name: jackett
    external: true
  emby:
    name: emby
    driver_opts:
      type: none
      device: ${SHARE_PATH}/.emby
      o: bind
  portainer_data:
  ddclient:

  # Volumes shared across containers
  # Add more share paths as needed
  downloads:
    name: downloads
    driver_opts:
      type: none
      device: ${DOWNLOADS_PATH}
      o: bind
  intermediate:
    name: intermediate
    driver_opts:
      type: none
      device: ${DOWNLOADS_PATH}/intermediate
      o: bind
  share1:
    name: share1
    driver_opts:
      type: none
      device: ${SHARE_PATH}
      o: bind
