entryPoints:
  http:
    address: ":80"
  https:
    address: ":443"

api:
  dashboard: true

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    watch: true
    exposedbydefault: false
  file:
    watch: true
    filename: "/etc/traefik/external.yaml"

certificatesResolvers:
  htpc:
    acme:
      email: "your-email@gmail.com"
      storage: "/etc/traefik/acme.json"
      httpChallenge:
        entryPoint: http

log:
  level: DEBUG
